<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-10-01T19:59:29 IST" name="Default suite" finished-at="2022-10-01T20:00:35 IST" duration-ms="66733">
    <groups>
    </groups>
    <test started-at="2022-10-01T19:59:29 IST" name="Default test" finished-at="2022-10-01T20:00:35 IST" duration-ms="66733">
      <class name="Module1_FB_Login_Test.TestClass">
        <test-method is-config="true" signature="OpenBrowser()[pri:0, instance:Module1_FB_Login_Test.TestClass@2e6a8155]" started-at="2022-10-01T19:59:29 IST" name="OpenBrowser" finished-at="2022-10-01T19:59:35 IST" duration-ms="6777" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OpenBrowser -->
        <test-method is-config="true" signature="LoginToApp()[pri:0, instance:Module1_FB_Login_Test.TestClass@2e6a8155]" started-at="2022-10-01T19:59:35 IST" name="LoginToApp" finished-at="2022-10-01T20:00:24 IST" duration-ms="48096" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginToApp -->
        <test-method signature="VerifyUSerID()[pri:0, instance:Module1_FB_Login_Test.TestClass@2e6a8155]" started-at="2022-10-01T20:00:24 IST" name="VerifyUSerID" finished-at="2022-10-01T20:00:24 IST" duration-ms="131" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Pass:Act & exp results are same expected [Santosh Jadhav] but found [Sandesh Jadhav]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Pass:Act & exp results are same expected [Santosh Jadhav] but found [Sandesh Jadhav]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at Module1_FB_Login_Test.TestClass.VerifyUSerID(TestClass.java:79)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyUSerID -->
        <test-method is-config="true" signature="LogoutFromApp(org.testng.ITestResult)[pri:0, instance:Module1_FB_Login_Test.TestClass@2e6a8155]" started-at="2022-10-01T20:00:24 IST" name="LogoutFromApp" finished-at="2022-10-01T20:00:32 IST" duration-ms="7994" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=VerifyUSerID status=FAILURE method=TestClass.VerifyUSerID()[pri:0, instance:Module1_FB_Login_Test.TestClass@2e6a8155] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LogoutFromApp -->
        <test-method is-config="true" signature="CloseBrowser()[pri:0, instance:Module1_FB_Login_Test.TestClass@2e6a8155]" started-at="2022-10-01T20:00:32 IST" name="CloseBrowser" finished-at="2022-10-01T20:00:35 IST" duration-ms="3671" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CloseBrowser -->
      </class> <!-- Module1_FB_Login_Test.TestClass -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
